GO
USE refuge_des_plaines;
GO

GRANT SELECT ON dbo.LOCALISATION TO UserExt;
GRANT SELECT ON dbo.ANIMAL TO UserExt;
GRANT SELECT ON dbo.ANIMAL TO Soigneur;
GRANT INSERT, SELECT, UPDATE ON dbo.SOIN TO Soigneur;
GRANT SELECt, UPDATE ON dbo.ANIMAL TO Medecin;
GRANT SELECt, UPDATE ON dbo.SOIN TO Medecin;
GRANT INSERT, SELECT, UPDATE ON dbo.Animal TO RespInscript;

--SELECT * FROM ANIMAL;
--SELECT * FROM EMPLOI;
--SELECT * FROM EMPLOYÉS;
--SELECT * FROM LOCALISATION;
--SELECT * FROM REFUGE;
--SELECT * FROM SOIN;