CREATE LOGIN Patrick WITH PASSWORD = 'tigrou007';
CREATE LOGIN Andre WITH PASSWORD = 'tigrou007';
CREATE LOGIN Pierre WITH PASSWORD = 'tigrou007';
CREATE LOGIN RespInscript WITH PASSWORD = 'tigrou007';
CREATE LOGIN Medecin WITH PASSWORD = 'tigrou007';
CREATE LOGIN Soigneur WITH PASSWORD = 'tigrou007';
CREATE LOGIN UserExt WITH PASSWORD = 'tigrou007';